name: "🛠 Bug Report"
description: "Bugに関しての報告です、発生するページ、操作流れ、スクリーンショットなどを記入してください"
title: "[DevTools Bug]: ここにタイトルを記入してください"
labels: ["bug"]
body:
- type: input
  attributes:
    label: ページのURL
    description: |
      Bugが発生するページのURLです
      ローカルURLでも良いですが貼ってください
      （デプロイURLがあればもっと理想です）
    placeholder: |
      http://localhost:3000/index.html
  validations:
    required: true
- type: textarea
  attributes:
    label: 操作の流れ
    description: |
      Bugを再現させるために、操作の流れを詳細に記入してください
    placeholder: |
      1. ホームページに行きます
      2. 右上のアイコンをクリックします、情報入力ページに行きます
      3. 情報入力ページで、アイテム名を記入します
  validations:
    required: true
- type: dropdown
  attributes:
    label: 発生の頻度
    description: |
      Bugの発生頻度を教えてください
    options:
      - 毎回発生します
      - よく発生します
      - ために発生します
      - 一回だけ発生します
  validations:
    required: true
- type: dropdown
  attributes:
    label: デバイス
    description: |
      デバイスの種類をお教えください
    options:
      - Mac
      - Windows
      - iPhone
      - Android
  validations:
    required: true
- type: input
  attributes:
    label: デバイスのバージョン
    description: |
      デバイスのバージョンをお教えください
    placeholder: |
      iPhone 15.4
  validations:
    required: false
- type: dropdown
  attributes:
    label: ブラウザー
    description: |
      ブラウザーの種類をお教えください
    options:
      - Mac
      - Windows
      - iPhone
      - Android
  validations:
    required: true
- type: input
  attributes:
    label: ブラウザーのバージョン
    description: |
      ブラウザーのバージョンをお教えください
    placeholder: |
      Chrome 99
  validations:
    required: false
- type: textarea
  attributes:
    label: 備考
    description: |
      補足事項があれば記入してください
  validations:
    required: false